export const NAV_ACTION = "NAV_ACTION";
export const pokerActions = {
    JOIN_ROOM : "JOIN_ROOM",
    CREATE_ROOM : "CREATE_ROOM",
    PUBLISH_STORY : "PUBLISH_STORY",
    SELECT_POINT : "SELECT_POINT",
    USER_LIST : "USER_LIST",
    STORY_DETAILS : "STORY_DETAILS",
    POINT_LIST : "POINT_LIST"
};

