export const NAV_ACTION = "NAV_ACTION";

export const pokerActions = {
    JOIN_ROOM : "JOIN_ROOM",
    CREATE_ROOM : "CREATE_ROOM",
    PUBLISH_STORY : "PUBLISH_STORY",
    SUBMIT_STORY : "SUBMIT_STORY",
    SELECT_POINT : "SELECT_POINT",
    STORY_LIST : "STORY_LIST",
};
export const configDataActions = {
    SET_PUBLISH:"SET_PUBLISH_STORY_CARD_VISIBILITY",
}

export const wsActions = {
    POINT_LIST : "POINT_LIST",
    ROOM_NUM : "ROOM_NUM",
    JOINED_AS_ADMIN : "JOINED_AS_ADMIN",
    P_M : "P_M",
    STORY_DETAILS : "STORY_DETAILS",
    PLAYER_LIST : "PLAYER_LIST",
    CLEAR_POINTS : "CLEAR_POINTS",
    RESET_ROOM : "RESET_ROOM"
}

